github: [metadata]

# Site settings
title: About
#baseurl: "/ap"
url: "https://hjje0ng.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Hyejeong Jeong
  #desc: Hello nice to meet you
  email: hjjeong20@korea.ac.kr
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  #github: hjje0ng
  linkedin: https://www.linkedin.com/in/hyejeong-jeong-92b199245/ 
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
#plugins:
#  - jekyll-paginate

# Permalinks
#permalink: /:year-:month-:day/:title
#paginate_path: "/portfolio/page:num/"
#paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
